# permissions for end users to edit csecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: csecret-editor-role
rules:
- apiGroups:
  - csecret.ssecrets
  resources:
  - csecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csecret.ssecrets
  resources:
  - csecrets/status
  verbs:
  - get
