---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - csecret.ssecrets
  resources:
  - csecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csecret.ssecrets
  resources:
  - csecrets/finalizers
  verbs:
  - update
- apiGroups:
  - csecret.ssecrets
  resources:
  - csecrets/status
  verbs:
  - get
  - patch
  - update
